#!/bin/bash

platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   platform='linux'
elif [[ "$unamestr" == 'FreeBSD' ]]; then
   platform='freebsd'
elif [[ "$unamestr" == 'Darwin' ]]; then
   platform='osx'
fi


function get_git_tag {
    git describe --tags `git rev-list --tags --max-count=1`
}

git_tag=$(get_git_tag)

if [[ $platform == 'linux' ]]; then
   sed -i -E "s/v[0-9]+\.[0-9]+\.[0-9]/$git_tag/" `git rev-parse --show-toplevel`/src/Constants.php
else
   sed -i "" -E "s/v[0-9]+\.[0-9]+\.[0-9]/$git_tag/" `git rev-parse --show-toplevel`/src/Constants.php
fi
git add `git rev-parse --show-toplevel`/src/Constants.php

echo 'Note: version number updated in src/Constants.php'