name: SDK chain tests

on:
  push:
    paths-ignore:
      - "**.md"

permissions:
  contents: read

env:
  # Allow ddev get to use a GitHub token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-standalone-bouncer:
    name: Run Standalone Bouncer tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/cs-standalone-php-bouncer/.github/workflows/php-sdk-development-tests.yml@main
    with:
      php_common_json: '["main"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
      remediation_engine_json: '["main"]'
      bouncer_lib_json: '["${{ github.ref_name }}"]'
