name: SDK chain tests
# To test all the SDK chain, we run Standalone Bouncer tests, as it depends on:
# - PHP Bouncer Lib
# - Remediation Engine Lib
# - LAPI client lib
# - PHP common lib

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

permissions:
  contents: read

env:
  # Allow ddev get to use a GitHub token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-standalone-bouncer:
    name: Run Standalone Bouncer tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/cs-standalone-php-bouncer/.github/workflows/php-sdk-development-tests.yml@736a2971d93dc6a7e9dc3a73051986b8f7e0b41a
    with:
      php_common_json: '["main"]'
      lapi_client_json: '["main"]'
      remediation_engine_json: '["main"]'
      bouncer_lib_json: '["${{ github.ref_name }}"]'
